Repository AY1920S2-CS2103T-W13-1/main, pull requests merged in 2020-04, with the labels that each got.

#247 Bug/fixmoretests
  src/main/java/seedu/eylah/diettracker/logic/commands/AddCommand.java
  src/main/java/seedu/eylah/diettracker/logic/commands/ListCommand.java
  src/main/java/seedu/eylah/diettracker/model/DietModel.java
  src/main/java/seedu/eylah/diettracker/model/DietModelManager.java
  src/test/java/seedu/eylah/diettracker/logic/LogicManagerTest.java
  src/test/java/seedu/eylah/diettracker/logic/commands/AddCommandTest.java
  src/test/java/seedu/eylah/diettracker/logic/commands/ListCommandTest.java
  src/test/java/seedu/eylah/diettracker/model/ModelStub.java
Labels: priority.High

#244 Removed SampleDataUtil for Expense Spliiter, added PaidCommandTest, some Parser Test
  .classpath
  src/main/java/seedu/eylah/Eylah.java
  src/test/data/JsonUserPrefsStorageTest/NotJsonFormatUserPrefs.json
  src/test/java/seedu/eylah/expensesplitter/logic/commands/PaidCommandTest.java
  src/test/java/seedu/eylah/expensesplitter/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/eylah/expensesplitter/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/eylah/expensesplitter/logic/parser/ParserUtilTest.java
  src/test/java/seedu/eylah/expensesplitter/model/ModelStub.java
  src/test/java/seedu/eylah/expensesplitter/model/ReceiptStub.java
Labels: priority.High, task.ExpenseSplitter

#249 Updated UG for Dry Run PE
  docs/UserGuide.adoc
  docs/diagrams/ExpenseSplitterActivityDiagramV2.puml
  docs/images/ExpenseSplitterActivityDiagramV2.png
Labels: type.UG

#248 List Commands Flag Refactor
  docs/UserGuide.adoc
  src/main/java/seedu/eylah/diettracker/logic/commands/ListCommand.java
  src/main/java/seedu/eylah/diettracker/logic/parser/CliSyntax.java
  src/main/java/seedu/eylah/diettracker/logic/parser/ListCommandParser.java
  src/main/java/seedu/eylah/diettracker/model/DietModelManager.java
  src/main/java/seedu/eylah/diettracker/model/food/Calories.java
  src/main/java/seedu/eylah/diettracker/model/food/Date.java
  src/test/java/seedu/eylah/diettracker/logic/commands/ListCommandTest.java
  src/test/java/seedu/eylah/diettracker/logic/parser/FoodBookParserTest.java
Labels: priority.High

#251 added help for Diet Tracker.
  src/main/java/seedu/eylah/diettracker/logic/commands/HelpCommand.java
Labels: priority.High, type.DG

#252 edited expense splitter activity diagram
  docs/diagrams/ExpenseSplitterActivityDiagramV2.puml
  docs/images/ExpenseSplitterActivityDiagramV2.png
Labels: type.UG

#254 Update HelpCommand for the Expense Splitter.
  src/main/java/seedu/eylah/expensesplitter/logic/commands/HelpCommand.java
  src/main/java/seedu/eylah/expensesplitter/logic/parser/ExpenseSplitterParser.java
Labels: priority.High, task.ExpenseSplitter

#296 Update UG for consult
  docs/UserGuide.adoc
  docs/images/expenseSplitterListAmountCommandSuccessPhoto.png
  docs/images/expenseSplitterPaidCommandSuccessPhoto.png
  docs/team/willyseahh.adoc
Labels: type.UG

#299 fix the expense splitter storage bugs and update PPP.
  docs/team/sheexiong.adoc
  src/main/java/seedu/eylah/Eylah.java
Labels: priority.High

#305 Updated PPP
  docs/team/jarrod-bob.adoc
Labels: priority.High

#312 Added Storage class for Self, to store user Height, Weight and Mode.
  src/main/java/seedu/eylah/Eylah.java
  src/main/java/seedu/eylah/commons/core/LogsCenter.java
  src/main/java/seedu/eylah/commons/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/eylah/commons/model/UserPrefs.java
  src/main/java/seedu/eylah/diettracker/logic/DietLogic.java
  src/main/java/seedu/eylah/diettracker/logic/DietLogicManager.java
  src/main/java/seedu/eylah/diettracker/model/DietModel.java
  src/main/java/seedu/eylah/diettracker/model/DietModelManager.java
  src/main/java/seedu/eylah/diettracker/model/Myself.java
  src/main/java/seedu/eylah/diettracker/model/ReadOnlyMyself.java
  src/main/java/seedu/eylah/diettracker/model/self/Height.java
  src/main/java/seedu/eylah/diettracker/model/self/Self.java
  src/main/java/seedu/eylah/diettracker/model/self/Weight.java
  src/main/java/seedu/eylah/diettracker/model/util/SampleDataUtil.java
  src/main/java/seedu/eylah/diettracker/storage/DietStorage.java
  src/main/java/seedu/eylah/diettracker/storage/DietStorageManager.java
  src/main/java/seedu/eylah/diettracker/storage/JsonAdaptedSelf.java
  src/main/java/seedu/eylah/diettracker/storage/JsonMyselfStorage.java
  src/main/java/seedu/eylah/diettracker/storage/JsonSerializableMyself.java
  src/main/java/seedu/eylah/diettracker/storage/MyselfStorage.java
  src/test/java/seedu/eylah/diettracker/logic/LogicManagerTest.java
  src/test/java/seedu/eylah/diettracker/logic/commands/AddCommandTest.java
  src/test/java/seedu/eylah/diettracker/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/eylah/diettracker/logic/commands/EditCommandTest.java
  src/test/java/seedu/eylah/diettracker/logic/commands/ListCommandTest.java
  src/test/java/seedu/eylah/diettracker/model/ModelManagerTest.java
  src/test/java/seedu/eylah/diettracker/model/ModelStub.java
  src/test/java/seedu/eylah/diettracker/testutil/TypicalMyself.java
Labels: priority.High, task.DietTracker

#311 updated DG use case and did a template of PaidCommand
  docs/DeveloperGuide.adoc
Labels: priority.High, type.DG

#313 Branch PE-D fixes
  docs/UserGuide.adoc
  src/main/java/seedu/eylah/diettracker/logic/commands/HeightCommand.java
  src/main/java/seedu/eylah/diettracker/logic/commands/HelpCommand.java
  src/main/java/seedu/eylah/diettracker/logic/commands/WeightCommand.java
  src/main/java/seedu/eylah/diettracker/logic/parser/ParserUtil.java
Labels: priority.High, task.DietTracker, type.UG

#348 Fix receipt storage not working issue.
  data/addressbook.json
  src/main/java/seedu/eylah/commons/core/GuiSettings.java
  src/main/java/seedu/eylah/commons/core/LogsCenter.java
  src/main/java/seedu/eylah/expensesplitter/logic/SplitterLogicManager.java
  src/main/java/seedu/eylah/expensesplitter/model/SplitterModelManager.java
  src/main/java/seedu/eylah/expensesplitter/model/receipt/UniqueReceiptList.java
Labels: priority.High, severity.High, task.ExpenseSplitter

#352 updated DG PaidCommand and fix additem -p bug
  docs/DeveloperGuide.adoc
  docs/diagrams/ExpenseSplitterPaidCommandActivityDiagram.puml
  docs/diagrams/ExpenseSplitterPaidCommandSequenceDiagram.puml
  docs/diagrams/ExpenseSplitterPaidCommandSequenceDiagram2.puml
  docs/images/ExpenseSplitterPaidCommandActivityDiagram.png
  docs/images/ExpenseSplitterPaidCommandSequenceDiagram.png
  docs/images/ExpenseSplitterPaidCommandSequenceDiagram2.png
  docs/images/ExpenseSplitterPaidCommandSequenceDiagramV2.png
  src/main/java/seedu/eylah/expensesplitter/logic/parser/AddItemCommandParser.java
  src/test/java/seedu/eylah/expensesplitter/logic/ExpenseSplitterLogicManagerTest.java
Labels: priority.High, task.ExpenseSplitter, type.DG

#351 Fixed Diet Tracker Bugs 1
  docs/UserGuide.adoc
  src/main/java/seedu/eylah/diettracker/logic/commands/HeightCommand.java
  src/main/java/seedu/eylah/diettracker/logic/commands/HelpCommand.java
  src/main/java/seedu/eylah/diettracker/logic/commands/WeightCommand.java
Labels: priority.High, severity.Medium, task.DietTracker, type.UG

#356 Show Remaining Calories
  src/main/java/seedu/eylah/diettracker/model/DietModel.java
  src/main/java/seedu/eylah/diettracker/model/DietModelManager.java
  src/main/java/seedu/eylah/diettracker/model/food/Calories.java
  src/test/java/seedu/eylah/diettracker/logic/commands/AddCommandTest.java
  src/test/java/seedu/eylah/diettracker/model/ModelStub.java
Labels: priority.High

#354 Fixed Diet Tracker Bugs 2
  src/main/java/seedu/eylah/diettracker/logic/commands/MetricsCommand.java
  src/main/java/seedu/eylah/diettracker/logic/parser/AddCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/FoodBookParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/MetricsCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/ParserUtil.java
  src/main/java/seedu/eylah/diettracker/model/DietModel.java
  src/main/java/seedu/eylah/diettracker/model/DietModelManager.java
  src/main/java/seedu/eylah/diettracker/model/food/Calories.java
  src/main/java/seedu/eylah/diettracker/model/food/Food.java
  src/test/java/seedu/eylah/diettracker/logic/commands/AddCommandTest.java
  src/test/java/seedu/eylah/diettracker/logic/commands/EditCommandTest.java
  src/test/java/seedu/eylah/diettracker/logic/commands/MetricsCommandTest.java
  src/test/java/seedu/eylah/diettracker/logic/parser/FoodBookParserTest.java
  src/test/java/seedu/eylah/diettracker/model/FoodBookTest.java
  src/test/java/seedu/eylah/diettracker/model/ModelStub.java
  src/test/java/seedu/eylah/diettracker/storage/JsonSerializableFoodBookTest.java
Labels: priority.High, task.DietTracker

#355 added ListReceipt and ListAmount for DG
  ExpenseSplitterActivityDiagram.png
  docs/DeveloperGuide.adoc
  docs/diagrams/ExpenseSplitterListAmountCommandActivityDiagram.puml
  docs/diagrams/ExpenseSplitterListAmountCommandSequenceDiagram.puml
  docs/diagrams/ExpenseSplitterListReceiptCommandActivityDiagram.puml
  docs/diagrams/ExpenseSplitterListReceiptCommandSequenceDiagram.puml
  docs/diagrams/ExpenseSplitterPaidCommandClassDiagram.puml
  docs/diagrams/ExpenseSplitterPaidCommandSequenceDiagram.puml
  docs/diagrams/ExpenseSplitterPaidCommandSequenceDiagram2.puml
  docs/images/ExpenseSplitterListAmountCommandActivityDiagram.png
  docs/images/ExpenseSplitterListAmountCommandSequenceDiagram.png
  docs/images/ExpenseSplitterListReceiptCommandActivityDiagram.png
  docs/images/ExpenseSplitterListReceiptCommandSequenceDiagram.png
  docs/images/ExpenseSplitterPaidCommandSequenceDiagram.png
  docs/images/ExpenseSplitterPaidCommandSequenceDiagram2.png
  docs/team/willyseahh.adoc
  src/main/java/seedu/eylah/expensesplitter/model/item/ItemName.java
  src/main/java/seedu/eylah/expensesplitter/model/item/ItemPrice.java
  src/main/java/seedu/eylah/expensesplitter/storage/JsonAdaptedItem.java
Labels: task.ExpenseSplitter, type.DG

#358 Throw exception when numDays parameter in list -d are negative or empty
  src/main/java/seedu/eylah/diettracker/logic/commands/ListCommand.java
  src/main/java/seedu/eylah/diettracker/logic/parser/ListCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/ParserUtil.java
Labels: priority.High

#361 Fixed UG for DT
  docs/UserGuide.adoc
  docs/diagrams/BmiActivityDiagram.puml
  docs/diagrams/DietTrackerActivityDiagram.puml
  docs/diagrams/DietTrackerDeleteFoodAcitivityDiagram.puml
  docs/diagrams/DietTrackerEditCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerHeightCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerListCommandSequenceDiagram2.puml
  docs/diagrams/DietTrackerMetricsCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerModeCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerWeightCommandSequenceDiagram.puml
  docs/team/jarrod-bob.adoc
Labels: priority.High, type.UG

#367 Refactor ArgumentMultimap, ArgumentTokenizer and Prefix to remove duplicate code.
  docs/diagrams/LogicClassDiagram.puml
  src/main/java/seedu/eylah/commons/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/eylah/commons/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/eylah/commons/logic/parser/Prefix.java
  src/main/java/seedu/eylah/diettracker/logic/parser/AddCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/eylah/diettracker/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/eylah/diettracker/logic/parser/BmiCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/CliSyntax.java
  src/main/java/seedu/eylah/diettracker/logic/parser/EditCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/ListCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/MetricsCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/ModeCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/Prefix.java
  src/main/java/seedu/eylah/expensesplitter/logic/parser/AddItemCommandParser.java
  src/main/java/seedu/eylah/expensesplitter/logic/parser/CliSyntax.java
  src/main/java/seedu/eylah/expensesplitter/logic/parser/PaidCommandParser.java
  src/test/java/seedu/eylah/diettracker/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/eylah/expensesplitter/logic/parser/ArgumentTokenizerTest.java
Labels: priority.High

#368 Refined and beefed up more comprehensive tests for expense splitter
  docs/diagrams/ExpenseSplitterClearReceiptCommandActivityDiagram.puml
  docs/diagrams/ExpenseSplitterClearReceiptCommandSequenceDiagram.puml
  docs/diagrams/ExpenseSplitterPaidCommandClassDiagram.puml
  src/main/java/seedu/eylah/commons/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/eylah/expensesplitter/model/SplitterModel.java
  src/main/java/seedu/eylah/expensesplitter/model/SplitterModelManager.java
  src/test/java/seedu/eylah/expensesplitter/logic/commands/AddItemCommandTest.java
  src/test/java/seedu/eylah/expensesplitter/logic/commands/BackCommandTest.java
  src/test/java/seedu/eylah/expensesplitter/logic/commands/ExitCommandTest.java
  src/test/java/seedu/eylah/expensesplitter/logic/commands/ListAmountCommandTest.java
  src/test/java/seedu/eylah/expensesplitter/logic/commands/ListReceiptCommandTest.java
  src/test/java/seedu/eylah/expensesplitter/logic/commands/PaidCommandTest.java
  src/test/java/seedu/eylah/expensesplitter/logic/parser/PaidCommandParserTest.java
  src/test/java/seedu/eylah/expensesplitter/model/ModelManagerTest.java
  src/test/java/seedu/eylah/expensesplitter/model/ModelStub.java
  src/test/java/seedu/eylah/expensesplitter/model/UserPrefsTest.java
Labels: priority.High

#366 New DG changes for DT
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/DietTrackerActivityDiagram.puml
  docs/diagrams/DietTrackerEditCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerHeightCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerListCommandAllSequenceDiagram.puml
  docs/diagrams/DietTrackerListCommandDaySequenceDiagram.puml
  docs/diagrams/DietTrackerListCommandTagSequenceDiagram.puml
  docs/diagrams/DietTrackerMetricsCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerModeCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerWeightCommandSequenceDiagram.puml
  docs/images/DietTrackerHeightCommandSequenceDiagram.png
  docs/images/DietTrackerWeightCommandSequenceDiagram.png
Labels: priority.High, task.DietTracker, type.DG

#372 Updated DG Prose and UG bits for DT.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/DietTrackerMetricsCommandSequenceDiagram.puml
  docs/images/DietTrackerBmiCommandActivityDiagram.png
  docs/images/DietTrackerMetricsCommandSequenceDiagram.png
Labels: priority.High, type.DG, type.UG

#369 Update All Diagram of Section 1 and refactor Model Class.
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/eylah/Eylah.java
  src/main/java/seedu/eylah/commons/logic/parser/CommonParser.java
  src/main/java/seedu/eylah/commons/model/ModelManager.java
  src/main/java/seedu/eylah/commons/storage/StorageManager.java
  src/main/java/seedu/eylah/diettracker/logic/commands/AddCommand.java
  src/main/java/seedu/eylah/diettracker/logic/commands/EditCommand.java
  src/main/java/seedu/eylah/diettracker/logic/parser/AddCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/BmiCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/DietCliSyntax.java
  src/main/java/seedu/eylah/diettracker/logic/parser/EditCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/FoodBookParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/ListCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/ModeCommandParser.java
  src/main/java/seedu/eylah/diettracker/model/DietModelManager.java
  src/main/java/seedu/eylah/diettracker/storage/DietStorageManager.java
  src/main/java/seedu/eylah/expensesplitter/logic/commands/AddItemCommand.java
  src/main/java/seedu/eylah/expensesplitter/logic/parser/AddItemCommandParser.java
  src/main/java/seedu/eylah/expensesplitter/logic/parser/ExpenseSplitterParser.java
  src/main/java/seedu/eylah/expensesplitter/logic/parser/SplitterCliSyntax.java
  src/main/java/seedu/eylah/expensesplitter/model/SplitterModel.java
  src/main/java/seedu/eylah/expensesplitter/model/SplitterModelManager.java
  src/main/java/seedu/eylah/expensesplitter/storage/SplitterStorageManager.java
  src/main/java/seedu/eylah/ui/Ui.java
  src/main/java/seedu/eylah/ui/UiManager.java
  src/test/java/seedu/eylah/diettracker/logic/commands/CommandTestUtil.java
  src/test/java/seedu/eylah/diettracker/logic/parser/FoodBookParserTest.java
  src/test/java/seedu/eylah/diettracker/testutil/FoodUtil.java
  src/test/java/seedu/eylah/expensesplitter/logic/commands/CommandTestUtil.java
  src/test/java/seedu/eylah/expensesplitter/model/ModelStub.java
Labels: priority.High, type.DG

#376 Updated DT DG with Diagrams
  docs/DeveloperGuide.adoc
  docs/diagrams/AddFoodActivityDiagram.puml
  docs/diagrams/DeleteFoodActivityDiagram.puml
  docs/diagrams/DeleteFoodSequenceDiagram.puml
  docs/diagrams/DietTrackerActivityDiagram.puml
  docs/diagrams/DietTrackerAddCommandActivityDiagram.puml
  docs/diagrams/DietTrackerAddCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerBmiCommandActivityDiagram.puml
  docs/diagrams/DietTrackerBmiCommandNILSequenceDiagram.puml
  docs/diagrams/DietTrackerBmiCommandNILSequenceDiagram2.puml
  docs/diagrams/DietTrackerBmiCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerBmiCommandSequenceDiagram2.puml
  docs/diagrams/DietTrackerDeleteCommandActivityDiagram.puml
  docs/diagrams/DietTrackerEditCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerHeightCommandActivityDiagram.puml
  docs/diagrams/DietTrackerHeightCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerListActivityDiagram.puml
  docs/diagrams/DietTrackerListCommandAllSequenceDiagram.puml
  docs/diagrams/DietTrackerListCommandDaySequenceDiagram.puml
  docs/diagrams/DietTrackerListCommandSequenceDiagram2.puml
  docs/diagrams/DietTrackerListCommandTagSequenceDiagram.puml
  docs/diagrams/DietTrackerMetricsCommandActivityDiagram.puml
  docs/diagrams/DietTrackerMetricsCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerModeCommandActivityDiagram.puml
  docs/diagrams/DietTrackerModeCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerWeightCommandActivityDiagram.puml
  docs/diagrams/DietTrackerWeightCommandSequenceDiagram.puml
  docs/images/DietTrackerAddCommandActivityDiagram.png
  docs/images/DietTrackerBmiCommandNILSequenceDiagram.png
  docs/images/DietTrackerBmiCommandNILSequenceDiagram2.png
  docs/images/DietTrackerBmiCommandSequenceDiagram.png
  docs/images/DietTrackerBmiCommandSequenceDiagram2.png
  docs/images/DietTrackerDeleteCommandActivityDiagram.png
  docs/images/DietTrackerDeleteCommandSequenceDiagram.png
  docs/images/DietTrackerEditCommandSequenceDiagram.png
  docs/images/DietTrackerHeightCommandActivityDiagram.png
  docs/images/DietTrackerListActivityDiagram.png
  docs/images/DietTrackerListCommandAllSequenceDiagram.png
  docs/images/DietTrackerListCommandDaySequenceDiagram.png
  docs/images/DietTrackerListCommandTagSequenceDiagram.png
  docs/images/DietTrackerMetricsCommandActivityDiagram.png
  docs/images/DietTrackerModeCommandActivityDiagram.png
  docs/images/DietTrackerModeCommandSequenceDiagram.png
  docs/images/DietTrackerWeightCommandActivityDiagram.png
Labels: priority.High, task.DietTracker, type.DG

#378 Updated more DT things
  docs/diagrams/DietTrackerEditCommandActivityDiagram.puml
  docs/diagrams/DietTrackerListCommandActivityDiagram.puml
  docs/images/DietTrackerAddCommandActivityDiagram.png
  docs/images/DietTrackerAddCommandSequenceDiagram.png
  docs/images/DietTrackerEditCommandActivityDiagram.png
  docs/images/DietTrackerListCommandActivityDiagram.png
  src/main/java/seedu/eylah/diettracker/logic/parser/BmiCommandParser.java
Labels: priority.High, task.DietTracker, type.DG

#379 updated DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ExpenseSplitterActivityDiagram.puml
  docs/diagrams/ExpenseSplitterListAmountCommandActivityDiagram.puml
  docs/diagrams/ExpenseSplitterListAmountCommandSequenceDiagram.puml
  docs/diagrams/ExpenseSplitterListReceiptCommandActivityDiagram.puml
  docs/diagrams/ExpenseSplitterListReceiptCommandSequenceDiagram.puml
  docs/diagrams/ExpenseSplitterPaidCommandActivityDiagram.puml
  docs/diagrams/ExpenseSplitterPaidCommandSequenceDiagram.puml
  docs/diagrams/ExpenseSplitterPaidCommandSequenceDiagram2.puml
  docs/images/ExpenseSplitterActivityDiagram.png
  docs/images/ExpenseSplitterListAmountCommandActivityDiagram.png
  docs/images/ExpenseSplitterListAmountCommandSequenceDiagram.png
  docs/images/ExpenseSplitterListReceiptCommandActivityDiagram.png
  docs/images/ExpenseSplitterListReceiptCommandSequenceDiagram.png
  docs/images/ExpenseSplitterPaidCommandActivityDiagram.png
  docs/images/ExpenseSplitterPaidCommandSequenceDiagram.png
  docs/images/ExpenseSplitterPaidCommandSequenceDiagram2.png
  docs/team/willyseahh.adoc
  src/test/java/seedu/eylah/expensesplitter/storage/JsonSerializablePersonAmountBookTest.java
  src/test/java/seedu/eylah/expensesplitter/storage/JsonUserPrefsSplitterStorageTest.java
Labels: type.DG

#383 PPP Changes
  docs/DeveloperGuide.adoc
  docs/team/jarrod-bob.adoc
Labels: priority.High

#385 Updated Dev Ops and Testing Links to reflect correct information.
  docs/DevOps.adoc
  docs/Testing.adoc
Labels: priority.High, type.DG

#386 Update Exit, Back and Help in UG and DoneReceipt in DG.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ExpenseSplitterDoneReceiptCommandActivityDiagram.puml
  docs/diagrams/ExpenseSplitterDoneReceiptCommandSequenceDiagram.puml
  docs/images/ExpenseSplitterDoneReceiptCommandActivityDiagram.png
  docs/images/ExpenseSplitterDoneReceiptCommandSequenceDiagram.png
Labels: type.DG, type.UG

#394 Rearrage Exit Command, Fix some hyperlink issue in UG.
  docs/UserGuide.adoc
Labels: type.UG

#396 Fixing 1 bug issue related to PersonAmountBook storage test, requesti…
  src/main/java/seedu/eylah/expensesplitter/model/PersonAmountBook.java
  src/test/data/JsonSerializablePersonAmountBookTest/typicalPersonsAmountBook.json
  src/test/java/seedu/eylah/expensesplitter/storage/JsonSerializablePersonAmountBookTest.java
  src/test/java/seedu/eylah/expensesplitter/testutil/TypicalPersons.java
Labels: type.Bug

#401 Updated DG for DT with class diagrams.
  docs/DeveloperGuide.adoc
  docs/diagrams/DietTrackerBmiCommandClassDiagram.puml
  docs/diagrams/DietTrackerHeightCommandClassDiagram.puml
  docs/diagrams/DietTrackerMetricsCommandClassDiagram.puml
  docs/diagrams/DietTrackerModeCommandClassDiagram.puml
  docs/diagrams/DietTrackerWeightCommandClassDiagram.puml
  src/main/java/seedu/eylah/diettracker/logic/commands/MetricsCommand.java
Labels: priority.High, task.DietTracker, type.DG

#405 Update DG for Logging, Configuration, Remove back and exit command, update use case.
  docs/DeveloperGuide.adoc
  docs/diagrams/ExpenseSplitterDoneReceiptCommandActivityDiagram.puml
  docs/images/ExpenseSplitterDoneReceiptCommandActivityDiagram.png
  docs/images/ExpenseSplitterDoneReceiptCommandClassDiagram.png
Labels: type.DG

#404 Fixed the DG image issue with class diagrams saved in wrong folder.
  docs/images/DietTrackerBmiCommandClassDiagram.png
  docs/images/DietTrackerHeightCommandClassDiagram.png
  docs/images/DietTrackerMetricsCommandClassDiagram.png
  docs/images/DietTrackerModeCommandClassDiagram.png
  docs/images/DietTrackerWeightCommandClassDiagram.png
Labels: priority.High, task.DietTracker, type.DG

#413 Updated DG and UG and PPP
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/jarrod-bob.adoc
Labels: priority.High, task.DietTracker, type.DG

#414 Finalised PPP
  docs/team/jarrod-bob.adoc
Labels: priority.High

#416 Updated DG for DT and UG for DT and PPP.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/jarrod-bob.adoc
Labels: priority.High, task.DietTracker, type.DG, type.UG

#418 Updated Willy PPP
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/ExpenseSplitterListAmountCommandClassDiagram.puml
  docs/diagrams/ExpenseSplitterListReceiptCommandClassDiagram.puml
  docs/diagrams/ExpenseSplitterPaidCommandClassDiagram.puml
  docs/images/ExpenseSplitterListAmountCommandClassDiagram.png
  docs/images/ExpenseSplitterListReceiptCommandClassDiagram.png
  docs/images/ExpenseSplitterPaidCommandClassDiagram.png
  docs/team/willyseahh.adoc
Labels: priority.High, task.ExpenseSplitter, type.DG

#423 FINAL CHANGES
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/[CS2103T-W13-01][Ng Jun Guang, Jarrod]UMLDiagrams.adoc
  docs/diagrams/DeleteFoodSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DietTrackerAddCommandClassDiagram.puml
  docs/diagrams/DietTrackerAddCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerBmiCommandClassDiagram.puml
  docs/diagrams/DietTrackerBmiCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerDeleteCommandClassDiagram.puml
  docs/diagrams/DietTrackerEditCommandActivityDiagram.puml
  docs/diagrams/DietTrackerEditCommandClassDiagram.puml
  docs/diagrams/DietTrackerEditCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerHeightCommandClassDiagram.puml
  docs/diagrams/DietTrackerHeightCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerListCommandActivityDiagram.puml
  docs/diagrams/DietTrackerListCommandAllSequenceDiagram.puml
  docs/diagrams/DietTrackerListCommandDaySequenceDiagram.puml
  docs/diagrams/DietTrackerListCommandTagSequenceDiagram.puml
  docs/diagrams/DietTrackerMetricsCommandClassDiagram.puml
  docs/diagrams/DietTrackerMetricsCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerModeCommandClassDiagram.puml
  docs/diagrams/DietTrackerModeCommandSequenceDiagram.puml
  docs/diagrams/DietTrackerWeightCommandClassDiagram.puml
  docs/diagrams/DietTrackerWeightCommandSequenceDiagram.puml
  docs/images/DietTrackerAddCommandSequenceDiagram.png
  docs/images/DietTrackerBmiCommandClassDiagram.png
  docs/images/DietTrackerBmiCommandSequenceDiagram.png
  docs/images/DietTrackerDeleteCommandClassDiagram.png
  docs/images/DietTrackerDeleteCommandSequenceDiagram.png
  docs/images/DietTrackerEditCommandClassDiagram.png
  docs/images/DietTrackerEditCommandSequenceDiagram.png
  docs/images/DietTrackerHeightCommandClassDiagram.png
  docs/images/DietTrackerHeightCommandSequenceDiagram.png
  docs/images/DietTrackerListCommandAllSequenceDiagram.png
  docs/images/DietTrackerListCommandDaySequenceDiagram.png
  docs/images/DietTrackerListCommandTagSequenceDiagram.png
  docs/images/DietTrackerMetricsCommandClassDiagram.png
  docs/images/DietTrackerMetricsCommandSequenceDiagram.png
  docs/images/DietTrackerModeCommandClassDiagram.png
  docs/images/DietTrackerModeCommandSequenceDiagram.png
  docs/images/DietTrackerWeightCommandClassDiagram.png
  docs/images/DietTrackerWeightCommandSequenceDiagram.png
  docs/team/jarrod-bob.adoc
  src/main/java/seedu/eylah/diettracker/logic/commands/HeightCommand.java
  src/main/java/seedu/eylah/diettracker/logic/commands/WeightCommand.java
  src/main/java/seedu/eylah/diettracker/logic/parser/HeightCommandParser.java
  src/main/java/seedu/eylah/diettracker/logic/parser/WeightCommandParser.java
Labels: priority.High, task.DietTracker, type.DG

#426 update UG to include success photos
  docs/UserGuide.adoc
Labels: type.UG

#427 Uploaded UG DT Photos.
  docs/UserGuide.adoc
  docs/images/dietTrackerAddCommandSuccessPhoto.png
  docs/images/dietTrackerBackCommandSuccessPhoto.png
  docs/images/dietTrackerBmiCommandSuccessPhoto.png
  docs/images/dietTrackerDeleteCommandSuccessPhoto.png
  docs/images/dietTrackerEditCommandSuccessPhoto.png
  docs/images/dietTrackerHeightCommandSuccessPhoto.png
  docs/images/dietTrackerListCommandSuccessPhoto.png
  docs/images/dietTrackerMetricsCommandSuccessPhoto.png
  docs/images/dietTrackerModeCommandSuccessPhoto.png
  docs/images/dietTrackerWeightCommandSuccessPhoto.png
Labels: priority.High, type.UG
